version: '3.5'

services:

  es_venus:
    image: jahrik/arm-elasticsearch:arm32v7
    ports:
      - "9200:9200"
    volumes:
      - /data:/var/lib/elasticsearch:rw
      - /etc/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      - /etc/elasticsearch/jvm.options:/etc/elasticsearch/jvm.options
    networks:
      - traefik
      - elk
    deploy:
      labels:
        traefik.enable: 1
        traefik.port: 9200
        traefik.backend: elk
        traefik.docker.network: traefik
      placement:
        constraints:
          - node.labels.arch == arm32v7
          - node.hostname == venus

  es_ninja:
    image: jahrik/arm-elasticsearch:arm32v7
    volumes:
      - /data:/var/lib/elasticsearch:rw
      - /etc/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      - /etc/elasticsearch/jvm.options:/etc/elasticsearch/jvm.options
    networks:
      - traefik
      - elk
    deploy:
      labels:
        traefik.enable: 1
        traefik.port: 9200
        traefik.backend: elk
        traefik.docker.network: traefik
      placement:
        constraints:
          - node.labels.arch == arm32v7
          - node.hostname == ninja

  es_oroku:
    image: jahrik/arm-elasticsearch:arm32v7
    volumes:
      - /data:/var/lib/elasticsearch:rw
      - /etc/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      - /etc/elasticsearch/jvm.options:/etc/elasticsearch/jvm.options
    networks:
      - traefik
      - elk
    deploy:
      labels:
        traefik.enable: 1
        traefik.port: 9200
        traefik.backend: elk
        traefik.docker.network: traefik
      placement:
        constraints:
          - node.labels.arch == arm32v7
          - node.hostname == oroku

networks:
  traefik:
    driver: overlay
    external: true
  elk:
    name: elk
    driver: overlay
