version: '3'

services:

  es_venus:
    image: jahrik/arm-elasticsearch:arm32v7
    ports:
      - "9200:9200"
    volumes:
      - /data:/var/lib/elasticsearch:rw
      - /etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /etc/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm32v7
          - node.hostname == venus
      restart_policy:
        delay: 30s
        max_attempts: 10
        window: 60s
      update_config:
        parallelism: 1
        monitor: 2m
        max_failure_ratio: 1
        failure_action: rollback
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 1000M
        reservations:
          cpus: '0.30'
          memory: 500M

  es_ninja:
    image: jahrik/arm-elasticsearch:arm32v7
    volumes:
      - /data:/var/lib/elasticsearch:rw
      - /etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /etc/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm32v7
          - node.hostname == ninja
      restart_policy:
        delay: 30s
        max_attempts: 10
        window: 60s
      update_config:
        parallelism: 1
        monitor: 2m
        max_failure_ratio: 1
        failure_action: rollback
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 1000M
        reservations:
          cpus: '0.30'
          memory: 500M

  es_oroku:
    image: jahrik/arm-elasticsearch:arm32v7
    volumes:
      - /data:/var/lib/elasticsearch:rw
      - /etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /etc/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm32v7
          - node.hostname == oroku
      restart_policy:
        delay: 30s
        max_attempts: 10
        window: 60s
      update_config:
        parallelism: 1
        monitor: 2m
        max_failure_ratio: 1
        failure_action: rollback
        delay: 10s
      resources:
        limits:
          cpus: '0.50'
          memory: 1000M
        reservations:
          cpus: '0.30'
          memory: 500M
