version: '3.5'

services:

  es_venus:
    image: jahrik/arm-elasticsearch:armv7l
    volumes:
      - /data:/var/lib/elasticsearch:rw
      - /etc/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      - /etc/elasticsearch/jvm.options:/etc/elasticsearch/jvm.options
    networks:
      - elk
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm32v7
          - node.hostname == venus

  es_ninja:
    image: jahrik/arm-elasticsearch:armv7l
    volumes:
      - /data:/var/lib/elasticsearch:rw
      - /etc/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      - /etc/elasticsearch/jvm.options:/etc/elasticsearch/jvm.options
    networks:
      - elk
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm32v7
          - node.hostname == ninja

  es_oroku:
    image: jahrik/arm-elasticsearch:armv7l
    volumes:
      - /data:/var/lib/elasticsearch:rw
      - /etc/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      - /etc/elasticsearch/jvm.options:/etc/elasticsearch/jvm.options
    networks:
      - elk
    deploy:
      placement:
        constraints:
          - node.labels.arch == arm32v7
          - node.hostname == oroku

  es_leona:
    image: jahrik/elasticsearch:x86_64
    ports:
      - "9200:9200"
    environment:
      # - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    volumes:
      - /data:/usr/share/elasticsearch/data:rw
      - /etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      # - /etc/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
    networks:
      - elk
    deploy:
      placement:
        constraints:
          - node.labels.arch == x86_64
          - node.hostname == leona

networks:
  elk:
    name: elk
    driver: overlay
