version: '3'

services:

  elasticsearch:
    image: jahrik/arm-elasticsearch:arm32v7
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.arch == arm32v7
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /data:/var/lib/elasticsearch:rw
      - /etc/elasticsearch/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
      - /etc/elasticsearch/jvm.options:/etc/elasticsearch/jvm.options
